# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-07 04:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentinCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Subscritptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=1000)),
                ('opt_in', models.BooleanField()),
                ('opt_in_source', models.CharField(max_length=1000)),
                ('preference_set_datetime', models.DateTimeField(blank=True)),
                ('full_name', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='studentincourse',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailouts.Subscritptions'),
        ),
    ]
