# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 04:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailouts', '0002_auto_20160614_0559'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterRecipients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_flag', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Newsletters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=1000)),
                ('email_body', models.TextField()),
                ('course_criteria', models.TextField()),
                ('demographic_criteria', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='newsletterrecipients',
            name='newsletter_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailouts.Newsletters'),
        ),
        migrations.AddField(
            model_name='newsletterrecipients',
            name='subscription_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailouts.Subscriptions'),
        ),
    ]
