# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-04 04:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailouts', '0003_auto_20160628_0411'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletters',
            name='sender_email',
            field=models.CharField(default='a.bakharia1@uq.edu.au', max_length=1000),
            preserve_default=False,
        ),
    ]
