# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-10 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailouts', '0005_auto_20170110_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='email_text',
            field=models.TextField(blank=True),
        ),
    ]
